// <auto-generated />
using System;
using EcoLife.HouseHoldApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoLife.HouseHoldApi.Migrations
{
    [DbContext(typeof(HouseHoldDbContext))]
    [Migration("20241111041903_first migration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoLife.HouseHoldApi.Models.HouseHoldEntity", b =>
                {
                    b.Property<int>("HouseHoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseHoldId"));

                    b.Property<double>("CoalUsage")
                        .HasColumnType("float");

                    b.Property<double>("ElectricityUsage")
                        .HasColumnType("float");

                    b.Property<double>("HouseHoldEmisssion")
                        .HasColumnType("float");

                    b.Property<double>("LPGUsage")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HouseHoldId");

                    b.ToTable("HouseHoldEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
