// <auto-generated />
using System;
using EcoLife.WasteManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoLife.WasteManagementApi.Migrations
{
    [DbContext(typeof(WasteManagementDbContext))]
    [Migration("20241111052516_waste management")]
    partial class wastemanagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoLife.WasteManagementApi.Models.WasteManagementEntity", b =>
                {
                    b.Property<int>("WateManagementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WateManagementId"));

                    b.Property<double>("CompostWaste")
                        .HasColumnType("float");

                    b.Property<double>("LandfillWaste")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("RecycledWaste")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WasteEmmision")
                        .HasColumnType("float");

                    b.HasKey("WateManagementId");

                    b.ToTable("WasteManagementEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
